ph: '/students/2023-2024/master/micromouth_marvels/working/PH.csv'
plaque: '/students/2023-2024/master/micromouth_marvels/working/Plaque.csv'
gum_bleeding: '/students/2023-2024/master/micromouth_marvels/working/Gum-Bleeding1.csv'
lifesum: '/students/2023-2024/master/micromouth_marvels/working/Lifesum.csv'
