my_data: '/students/2023-2024/master/micromouth_marvels/working/Basic Expriments.xlsx'

ph: '/students/2023-2024/master/micromouth_marvels/working/PH.csv'
plaque: '/students/2023-2024/master/micromouth_marvels/working/Plaque.csv'
gum_bleeding: '/students/2023-2024/master/micromouth_marvels/working/Gum-Bleeding.csv'
lifesum: '/students/2023-2024/master/micromouth_marvels/working/Lifesum.csv'

ph2: '/students/2023-2024/master/micromouth_marvels/working/PH 2.csv'
plaque2: '/students/2023-2024/master/micromouth_marvels/working/Plaque 2.csv'
gum_bleeding2: '/students/2023-2024/master/micromouth_marvels/working/Gum bleeding 2.csv'
