# CONFIGURE KRAKEN FILES (OR BRACKEN)
kraken_files:
  before_measurement_file: '/students/2023-2024/master/micromouth_marvels/working/R1.txt'  # add path!
  after_measurement_file: '/students/2023-2024/master/micromouth_marvels/working/R2.txt'   # add path!

# OPTIONAL: specify species to solely include in the analysis
# if empty, all species will be included
selected_species: 
#  - 'species'

# OPTIONAL: top N species (based on largest sample proportion) to show in plot
# if not provided, all species will be shown
top_n_species: 20
